-- XPMon saved data
XPMon_DATA = {};
XPMon_USER_CONFIG = {};

XPMON_DEBUG = true;
XPMON_NAME = "XPMon";
XPMON_SOURCE_KILL = "MOB KILL";
XPMON_SOURCE_QUEST = "QUEST";
XPMON_SOURCE_DUNGEON = "LOOKING FOR DUNGEON";
XPMON_SOURCE_PROFESSION = "PROFESSION";
XPMON_SOURCE_PET_BATTLE = "PET BATTLE";
XPMON_SOURCE_EXPLORATION = "EXPLORATION";
XPMON_SOURCE_BATTLEGROUND = "BATTLEGROUND";
XPMON_XP_EVENT_DEFAULT = {
    source = "Unknown",
    experience = 0,
    rested = 0,
    details = {}
}